stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "image-name"
  IMAGE_TAG: "latest"
  REGISTRY_URL: "registry-url"

build:
  stage: build
  script:
    - docker build -t $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  script:
    - kubectl apply -f kubernetes/deployment.yaml
    - kubectl apply -f kubernetes/service.yaml